version: '1'

services:
  database:
    image: postgres
    container_name: photomaster-database
    env_file:
      - ./server/.env
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgressql

volumes:
  database:
